ResidenLLC/openemr

docker/development-easy-macos/docker-compose.yml, interface/main/tabs/main.php, interface/themes/colors/style_residen.scss, library/globals.inc.php, package-lock.json, package.json, version.php
=> Revert "Revert "Colors scheme""

interface/patient_file/front_payment.php, interface/patient_file/front_payment_cc.php
=> WIP - Stripe Transaction Update Metadata

interface/patient_file/front_payment.php, interface/patient_file/front_payment_cc.php
=> Production - Stripe transaction metadata

.github/workflows/deploy-tfa-emr.yaml, interface/patient_file/printed_fee_sheet.php, version.php
=> PDF Adjustments

interface/modules/custom_modules/oe-module-patient-sync-residen/composer.json, interface/modules/custom_modules/oe-module-patient-sync-residen/info.txt, interface/modules/custom_modules/oe-module-patient-sync-residen/openemr.bootstrap.php, interface/modules/custom_modules/oe-module-patient-sync-residen/src/Bootstrap.php, interface/modules/custom_modules/oe-module-patient-sync-residen/src/GlobalConfig.php, interface/modules/custom_modules/oe-module-patient-sync-residen/src/Module.php, interface/modules/custom_modules/oe-module-patient-sync-residen/src/PatientSyncService.php
=> Added emr sync module.

interface/patient_file/front_payment.php, interface/patient_file/front_payment_cc.php, interface/reports/pat_ledger.php
=> Stripe transaction metadata

interface/modules/custom_modules/oe-module-patient-sync-residen/readme, interface/modules/custom_modules/oe-module-patient-sync-residen/src/AppointmentStatusRestController.php, interface/modules/custom_modules/oe-module-patient-sync-residen/src/Bootstrap.php
=> added the api for the appointments statuses

interface/modules/custom_modules/oe-module-patient-sync-residen/composer.json, interface/modules/custom_modules/oe-module-patient-sync-residen/info.txt, interface/modules/custom_modules/oe-module-patient-sync-residen/openemr.bootstrap.php, interface/modules/custom_modules/oe-module-patient-sync-residen/readme, interface/modules/custom_modules/oe-module-patient-sync-residen/src/AppointmentCategoryRestController.php, interface/modules/custom_modules/oe-module-patient-sync-residen/src/AppointmentStatusRestController.php, interface/modules/custom_modules/oe-module-patient-sync-residen/src/Bootstrap.php, interface/modules/custom_modules/oe-module-patient-sync-residen/src/GlobalConfig.php, interface/modules/custom_modules/oe-module-patient-sync-residen/src/Module.php, interface/modules/custom_modules/oe-module-patient-sync-residen/src/PatientSyncService.php, interface/modules/custom_modules/oe-module-patient-sync-residen/src/PaymentRestController.php, interface/modules/custom_modules/oe-module-patient-sync-residen/src/PaymentService.php
=> Filtered appointments categories for patient only

docker/residen-production/hilder-compose.yml, docker/residen-production/openemr.sh, docker/residen-production/production-compose.yml
=> Fix file permissions & configure EBS volume

interface/modules/custom_modules/oe-module-patient-sync-residen/readme, interface/modules/custom_modules/oe-module-patient-sync-residen/src/AppointmentRoomRestController.php, interface/modules/custom_modules/oe-module-patient-sync-residen/src/Bootstrap.php
=> Added the api endpoint for appointment rooms

docker/residen-production/hilder-compose.yml, docker/residen-production/openemr.sh, docker/residen-production/production-compose.yml
=> Fix container restart issue

docker/residen-production/openemr.sh
=> Prevent poweroff cache corruption

interface/modules/custom_modules/oe-module-patient-sync-residen/src/PatientSyncService.php
=> Updated the api sync for patients

interface/modules/custom_modules/oe-module-patient-sync-residen/src/CustomAppointmentRestController.php
=> Fix UUID not showing fine

interface/modules/custom_modules/oe-module-patient-sync-residen/src/PatientSyncService.php
=> Fix pid when creating updating a patient

interface/modules/custom_modules/oe-module-patient-sync-residen/src/Bootstrap.php, interface/modules/custom_modules/oe-module-patient-sync-residen/src/PatientSyncService.php
=> Comment logs

interface/modules/custom_modules/oe-module-patient-sync-residen/src/AppointmentCategoryRestController.php
=> Category color

interface/modules/custom_modules/oe-module-patient-sync-residen/src/AppointmentRestController.php
=> Link appointment with encounter when status changes and patient arrived

interface/modules/custom_modules/oe-module-patient-sync-residen/src/PaymentService.php
=> Try to fix problem with payment service, encounter not found for patient

interface/modules/custom_modules/oe-module-patient-sync-residen/src/PaymentService.php
=> Custom module residen sync
